"""Initial migration with Character and Spell models

Revision ID: 7a0d18ac2915
Revises: 
Create Date: 2025-05-15 20:43:49.503551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a0d18ac2915'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backgrounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('skill_prof', sa.JSON(), nullable=True),
    sa.Column('tool_prof', sa.JSON(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('equipment', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index')
    )
    op.create_table('char_feats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('char_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_proficient', sa.Boolean(), nullable=True),
    sa.Column('is_expertise', sa.Boolean(), nullable=True),
    sa.Column('custom_bonus', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('char_spells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index')
    )
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('hit_dice', sa.String(), nullable=False),
    sa.Column('hp', sa.String(), nullable=False),
    sa.Column('proficiencies', sa.JSON(), nullable=False),
    sa.Column('starting_equipment', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('req', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index')
    )
    op.create_table('inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rarity', sa.Text(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('creature_type', sa.String(), nullable=True),
    sa.Column('size', sa.Text(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('ability_bonuses', sa.JSON(), nullable=True),
    sa.Column('age', sa.Text(), nullable=True),
    sa.Column('alignment', sa.Text(), nullable=True),
    sa.Column('starting_proficiencies', sa.JSON(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('traits', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ability_score', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('char_class', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('race', sa.String(length=50), nullable=False),
    sa.Column('background', sa.String(length=100), nullable=False),
    sa.Column('alignment', sa.String(length=50), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('dexterity', sa.Integer(), nullable=True),
    sa.Column('constitution', sa.Integer(), nullable=True),
    sa.Column('intelligence', sa.Integer(), nullable=True),
    sa.Column('wisdom', sa.Integer(), nullable=True),
    sa.Column('charisma', sa.Integer(), nullable=True),
    sa.Column('armor_class', sa.Integer(), nullable=True),
    sa.Column('initiative', sa.Integer(), nullable=True),
    sa.Column('speed', sa.String(length=20), nullable=True),
    sa.Column('hp', sa.String(length=20), nullable=True),
    sa.Column('hit_dice', sa.String(length=20), nullable=True),
    sa.Column('death_saves', sa.String(length=20), nullable=True),
    sa.Column('weapon_profs', sa.Text(), nullable=True),
    sa.Column('armor_profs', sa.Text(), nullable=True),
    sa.Column('tool_profs', sa.Text(), nullable=True),
    sa.Column('languages', sa.Text(), nullable=True),
    sa.Column('equipment', sa.Text(), nullable=True),
    sa.Column('racial_traits', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_feats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('index', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level_req', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index')
    )
    op.create_table('race_traits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level_req', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index')
    )
    op.create_table('subclasses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('char_class_id', sa.Integer(), nullable=True),
    sa.Column('index', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['char_class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subraces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index')
    )
    op.create_table('spells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('school', sa.String(length=100), nullable=True),
    sa.Column('casting_time', sa.String(length=100), nullable=True),
    sa.Column('spell_range', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('components', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('higher_levels', sa.Text(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subclass_feats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subclass_id', sa.Integer(), nullable=True),
    sa.Column('index', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level_req', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['subclass_id'], ['subclasses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subrace_traits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subrace_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level_req', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['subrace_id'], ['subraces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subrace_traits')
    op.drop_table('subclass_feats')
    op.drop_table('spells')
    op.drop_table('subraces')
    op.drop_table('subclasses')
    op.drop_table('race_traits')
    op.drop_table('class_feats')
    op.drop_table('characters')
    op.drop_table('users')
    op.drop_table('skills')
    op.drop_table('races')
    op.drop_table('items')
    op.drop_table('inventories')
    op.drop_table('feats')
    op.drop_table('classes')
    op.drop_table('char_spells')
    op.drop_table('char_skills')
    op.drop_table('char_feats')
    op.drop_table('backgrounds')
    # ### end Alembic commands ###
